---
- name: Download Helm
  get_url:
    url: "{{ helm_url }}"
    dest: /tmp/get_helm.sh
    mode: 0775
  ignore_errors: true
  register: download

- name: Instalando Helm
  shell:
    /tmp/get_helm.sh
  when:
    - download.failed | bool == false
  register: isntall_helm

- name:
  debug: var=isntall_helm
